#genesis config stand

# Environment settings
#-------------------------------------------
sim: genesis
robots: [g1_slider]
fix_base_link: true
task: chairman
decimation: 5
num_envs: 1
headless: false
add_table: true
env_spacing: 4.0
train_or_eval: eval_video #load_and_train #train_dagger #eval_video



#camera configuration
#---------------------------------------
#(Pro evaluaci je potřeba odkomentovat)
#---------------------------------------
# cameras:
#    camera1:
#      type: PinholeCameraCfg
#      params:
#        name: camera0
#        pos: [3.0, -3.0, 3.0]
#        look_at: [0.0, 0.0, 0.0]
#        width: 640
#        height: 360
      #  mount_to: g1_slider
      #  mount_link: head_link
      #  mount_pos: [0.09, 0.0, 0.5]
      #  mount_quat: [0.5, 0.5, -0.5, -0.5]


# Train or Eval settings
#-------------------------------------------
force: false

#Eveluation settings
#------------------------------------------
#load_model_path: ./my_env/output/ppo_models/run_2025-10-16_13-59-07/model_80003072
#load_model_path: ./config_run/output/ppo_model/run_2026-03-02_14_chairman/
load_model_path: ./config_run/output/ppo_model_cluster/run_2026-03-02_18_chairman/model_410328000
#load_model_path: ./config_run/output/ppo_model_cluster/run_2026-02-26_18_chairman/
video_save_path: ./config_run/output/eval_videos/chair_man_5.mp4
eval_episodes: 2
eval_max_steps: 1000


# PPO training settings
#-------------------------------------------
total_timesteps: 400_000_000
model_save_path: ./config_run/output/ppo_model
model_save_freq: 10_000_000
tensorboard_log: ./config_run/output/tensorboard


# PPO parameters
#-------------------------------------------
net_arch_pivf: true
net_arch_pi: [512, 256, 128]  # Větší síť, humanoid má 30+ kloubů
net_arch_vf: [512, 256, 128]

learning_rate: 0.0005     # Mírně vyšší LR díky obrovskému batch size (běžně 3e-4 až 1e-3)
n_steps: 32               # Kratší rollouty (častější updaty sítě). Pro 9k envs stačí bohatě 32 nebo 64
batch_size: 72000         # MASIVNÍ batch size. (Vzorec: num_envs * n_steps / počet_minibatchů -> 9000*32 / 4)
n_epochs: 5               # Počet průchodů bufferem (standard v RSL_RL je 4 nebo 5)
gamma: 0.99               # Klasika, optimální pro běžný horizon
gae_lambda: 0.95          # Klasika
clip_range: 0.2           # Klasika
ent_coef: 0.001           # Lehká entropie (0.01 - 0.001) pro podporu explorace u těžkých úloh, aby robot "neztuhl"
vf_coef: 1.0              # Default je 0.5, ale u složitých odměn (stage) pomáhá 1.0 lépe predikovat Value funkci
max_grad_norm: 1.0
