#genesis config stand

# Environment settings
#-------------------------------------------
sim: genesis
robots: [g1_slider_simple]
fix_base_link: true
task: chairmansimple
decimation: 5
num_envs: 9000
headless: true
add_table: true
env_spacing: 4.0
train_or_eval: train #load_and_train #train_dagger #eval_video

# Light configuration
#---------------------------------------
# lights:
#   my_positional_light:
#     type: CylinderLightCfg
#     params:
#       pos: [0.0, 0.0, 0.8]       # Pozice světla [x, y, z] (např. 3.5m nad zemí)
#       color: [1.0, 0.95, 0.9]    # Barva světla (např. lehce do žluta)
#       intensity: 50000.0         # Lokální světla potřebují velkou hodnotu
#       radius: 0.5                # Poloměr z vaší konfigurace
#       length: 1.0                # Délka z vaší konfigurace

#camera configuration
#---------------------------------------
#(Pro evaluaci je potřeba odkomentovat)
#---------------------------------------
# cameras:
#    camera1:
#      type: PinholeCameraCfg
#      params:
#        name: camera0
#        pos: [3.0, -3.0, 3.0]
#        look_at: [0.0, 0.0, 0.0]
#        width: 1024
#        height: 640
#        focal_length: 4.0
#        mount_to: g1_slider
#        mount_link: head_link
#        mount_pos: [0.09, 0.0, 0.5]
#        mount_quat: [0.5, 0.5, -0.5, -0.5]


# Train or Eval settings
#-------------------------------------------
force: false

#Eveluation settings
#------------------------------------------
#load_model_path: ./my_env/output/ppo_models/run_2025-10-16_13-59-07/model_80003072
load_model_path: ./config_run/output/ppo_model/run_2026-04-15_18_chairmansimple/model_120096000
#load_model_path: ./config_run/output/ppo_model_cluster/run_2026-04-10_13_chairman/
#load_model_path: ./config_run/output/ppo_model_cluster/run_2026-04-02_20_chairman/model_970776000
#load_model_path: ./config_run/output/ppo_model_cluster/run_2026-03-13_14_chairman_top/model_200070000
video_save_path: ./config_run/output/eval_videos/chair_man_8.mp4
eval_episodes: 1
eval_max_steps: 1000


# PPO training settings
#-------------------------------------------
total_timesteps: 1_000_000_000
model_save_path: ./config_run/output/ppo_model
model_save_freq: 10_000_000
tensorboard_log: ./config_run/output/tensorboard


# PPO parameters
#-------------------------------------------
net_arch_pivf: true
net_arch_pi: [64, 64, 64]
net_arch_vf: [64, 64, 64]

learning_rate: 0.0003
n_steps: 32
batch_size: 72000
n_epochs: 4
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.002
vf_coef: 1.0
max_grad_norm: 1.0
# DAgger settings
#-------------------------------------------
dagger_store_per_step: 32
dagger_train_every: 20
dagger_updates_per_train: 10
dagger_batch_size: 512
dagger_buffer_steps: 4000
beta_start: 1.0
beta_decay: 0.9995
