#genesis config stand

# Environment settings
#-------------------------------------------
sim: genesis
robots: [g1_with_hands]
task: reachposori
decimation: 5
num_envs: 1
headless: false
add_table: true
fix_base_link: true

#camera configuration
#---------------------------------------
#(Pro evaluaci je potřeba odkomentovat)
#---------------------------------------
cameras:
   camera1:
     type: PinholeCameraCfg
     params:
       name: camera0
       pos: (1.5, -1.5, 1.5)
       look_at: (0.0, 0.0, 0.0)
       width: 1024
       height: 1024



# Train or Eval settings
#-------------------------------------------
train_or_eval: eval

#Eveluation settings
#------------------------------------------
#load_model_path: ./my_env/output/ppo_models/run_2025-10-16_13-59-07/model_80003072
#load_model_path: ./config_run/output/ppo_model_cluster/ppo_models/run_2025-10-16_14-06-35/model_100000000
#load_model_path: ./config_run/output/ppo_model/run_2025-10-23_15_reachposori/model_90000000
#load_model_path: ./config_run/output/ppo_model_cluster/run_2025-10-31_17_reachposori/model_200000000
load_model_path: ./config_run/output/ppo_model_cluster/tranining_1_11/run_2025-10-24_11_reachposori/model_370033300
video_save_path: ./config_run/output/eval_videos/reah_pos_ori_eval.mp4
eval_episodes: 1000


# PPO training settings
#-------------------------------------------
total_timesteps: 90_000_000
model_save_path: ./config_run/output/ppo_model
model_save_freq: 10_000_000


# PPO parameters
#-------------------------------------------
net_arch: [128, 128, 128]

learning_rate: 0.0003
n_steps: 128
batch_size: 256
n_epochs: 4
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
ent_coef: 0.01

tensorboard_log: ./config_run/output/tensorboard
