#genesis config stand

# Environment settings
#-------------------------------------------
sim: genesis
robots: [g1_with_hands_simple]
task: reachposori
decimation: 5
num_envs: 4500
headless: true
add_table: true
fix_base_link: true

#camera configuration
#---------------------------------------
#(Pro evaluaci je potřeba odkomentovat)
#---------------------------------------
# cameras:
#    camera1:
#      type: PinholeCameraCfg
#      params:
#        name: camera0
#        pos: (1.5, -1.5, 1.5)
#        look_at: (0.0, 0.0, 0.0)
#        width: 1024
#        height: 1024



# Train or Eval settings
#-------------------------------------------
load_model_path: ./config_run/output/ppo_model_cluster/run_2025-12-09_19_reachposori/model_90000000
train_or_eval: train

#Eveluation settings
#------------------------------------------
eval_freq: 10000000
n_eval_episodes: 1
eval_max_steps: 300

# PPO training settings
#-------------------------------------------
total_timesteps: 200_000_000
model_save_path: ./config_run/output/ppo_model
model_save_freq: 10_000_000
tensorboard_log: ./config_run/output/tensorboard
#eval during training settings
#-------------------------------------------
eval_freq: 10000000
n_eval_episodes: 1
eval_max_steps: 200

# PPO parameters
#-------------------------------------------
