#genesis config stand

# Environment settings
sim: genesis
robots: [g1_with_hands]
task: walk_new
decimation: 5
num_envs: 4

headless: false
add_table: true
#sensors configuration
sensors:
  sensor1:
    type: GyroSensorCfg
    params:
      name: gyro0
      pos: (0.0, 0.0, 0.0)
      mount_to: g1_with_hands
      mount_link: torso_link
  sensor2:
    type: CommandCfg
    params:
      name: command0
#external forces


force: true
force_x_min: -500.0
force_x_max: 500.0
force_y_min: -50.0
force_y_max: 50.0
#camera configuration
#---------------------------------------
#(Pro evaluaci je potřeba odkomentovat)
#---------------------------------------

# cameras:
#    camera1:
#      type: PinholeCameraCfg
#      params:
#        name: camera0
#        pos: (1.5, -1.5, 1.5)
#        look_at: (0.0, 0.0, 0.0)
#        width: 1024
#        height: 1024



# Training settings
train_or_eval: train


#eveluation settings
#load_model_path: ./my_env/output/ppo_models/run_2025-10-16_13-59-07/model_80003072
load_model_path: ./my_env/output/ppo_models/run_2025-10-15_20-22-31/model_80000000
video_save_path: ./config_run/output/eval_videos/walk_eval.mp4
eval_episodes: 10000


# PPO training settings
total_timesteps: 200_000_000
model_save_path: ./config_run/output/ppo_model
model_save_freq: 10_000_000

# Eval settings
eval_model_path:

# PPO parameters
net_arch_pivf: true
net_arch_pi: [256,256,128]
net_arch_vf: [256,256,128]
learning_schedule: linear
learning_rate: 3e-4
n_steps: 2048
batch_size: 512
n_epochs: 10
gamma: 0.99
gae_lambda: 0.97
clip_range: 0.2
ent_coef: 0.001
vf_coef: 0.5
max_grad_norm: 0.5

tensorboard_log: ./config_run/output/tensorboard
