#genesis config stand

# Environment settings
#-------------------------------------------
sim: genesis
robots: [g1_with_hands]
fix_base_link: false
task: chairman #chairmansimplegrpo # use chairmansimplegaussiangrpo for Gaussian-splat visual room
decimation: 5
num_envs: 1
headless: false
add_table: true
env_spacing: 4.0
train_or_eval: eval_video  #load_and_train #train_dagger #eval_video #eval_dagger_video #train_grpo #eval_grpo_video

# Light configuration
#---------------------------------------
# lights:
#   my_positional_light:
#     type: CylinderLightCfg
#     params:
#       pos: [0.0, 0.0, 0.8]       # Pozice světla [x, y, z] (např. 3.5m nad zemí)
#       color: [1.0, 0.95, 0.9]    # Barva světla (např. lehce do žluta)
#       intensity: 50000.0         # Lokální světla potřebují velkou hodnotu
#       radius: 0.5                # Poloměr z vaší konfigurace
#       length: 1.0                # Délka z vaší konfigurace

#camera configuration
#---------------------------------------
#(Pro evaluaci je potřeba odkomentovat)
#---------------------------------------
cameras:
   camera1:
     type: PinholeCameraCfg
     params:
       name: camera0
       pos: [-4.0, -4.0, 4.0]
       look_at: [0.0, 0.0, 0.0]
       width: 1024 #128
       height: 640 #128
      #  focal_length: 6.0 #6
      #  mount_to: g1_slider_simple
      #  mount_link: head_link
      #  mount_pos: [0.09, 0.0, 0.5]
      #  mount_quat: [0.5, 0.5, -0.5, -0.5]

# cameras:
#    camera1:
#      type: PinholeCameraCfg
#      params:
#        name: camera0
#        pos: [3.0, -3.0, 3.0]
#        look_at: [0.0, 0.0, 0.0]
#        width: 128
#        height: 128
#        focal_length: 6.0 #6
#        mount_to: g1_slider_simple
#        mount_link: head_link
#        mount_pos: [0.09, 0.0, 0.5]
#        mount_quat: [0.5, 0.5, -0.5, -0.5]


# Train or Eval settings
#-------------------------------------------
force: false

#Eveluation settings
#------------------------------------------
#load_model_path: ./config_run/output/ppo_model/run_2026-04-16_18_chairmansimple/model_50040000
#load_model_path: ./config_run/output/ppo_model/run_2026-05-06_18_chairmansimple/
#load_model_path: ./config_run/output/ppo_model/dagger4/student_model_step_70000.pth
#load_model_path: ./config_run/output/ppo_model/run_2026-05-06_18_chairmansimple/model_560344000

#load_model_path: ./config_run/output/ppo_model_cluster/run_2026-04-16_18_chairman/
#load_model_path: ./config_run/output/ppo_model_cluster/run_2026-04-02_20_chairman/model_970776000
#load_model_path: ./config_run/output/ppo_model_cluster/run_2026-03-13_14_chairman_top/model_200070000
#load_model_path: ./config_run/output/grpo_model/student_grpo_step_145.pth
load_model_path: ./config_run/output/ppo_models/run_2026-08-21_10_chairman/model_840420000
video_save_path: ./config_run/output/eval_videos/chair_man_21.mp4
eval_episodes: 1000
eval_max_steps: 1000
eval_total_step_cap: 100
eval_count_timeouts_as_failures: true
