# genesis config

# Environment settings
sim: genesis
robots: [g1]
task: humanoidbench:Walk
decimation: 5
num_envs: 1
headless: false
add_table: true

# Training settings
load_model_path: None
train_or_eval: train
total_timesteps: 60_000_000
model_save_path: ./saved_models
model_save_freq: 500_000

# Eval settings
eval_model_path: ./saved_models/1757079169/model_1000192


# PPO parameters
learning_rate: 0.0003
n_steps: 256
num_batch: 64
n_epochs: 4

# Learning rate schedule
use_lr_schedule: true
lr_schedule_type: linear  # Optional: linear, constant, cosine
final_lr_fraction: 0.1    # Optional: final learning rate is 10% of initial learning rate

# Wandb settings
use_wandb: false
wandb_project: humanoidbench_rl_training
wandb_entity: <YOUR_WANDB_ENTITY>
