sim: genesis
robots: [g1_with_hands]
fix_base_link: false
task: chairmanseparate
decimation: 5
num_envs: 100
headless: true
add_table: true
env_spacing: 4.0
train_or_eval: eval
reset_to_stage0: true
use_snapshot_curriculum: false
snapshot_save_probability: 0.0
load_model_path: ./config_run/output/ppo_models_separate/run_CHANGE_ME
# load_model_checkpoint: 50000000
eval_episodes: 100
eval_max_steps: 6000
policies:
  waist: {action_groups: [waist], observation_groups: [joint_positions, robot_body_states, pelvis_velocity, previous_policy_actions]}
  right_arm: {action_groups: [right_arm], observation_groups: [joint_positions, right_hand_task, pelvis_velocity, chair_geometry, stage, previous_policy_actions]}
  left_arm: {action_groups: [left_arm], observation_groups: [joint_positions, left_hand_task, pelvis_velocity, chair_geometry, stage, previous_policy_actions]}
  right_fingers: {action_groups: [right_fingers], observation_groups: [joint_positions, right_hand_task, fingertip_forces, stage, previous_policy_actions]}
  left_fingers: {action_groups: [left_fingers], observation_groups: [joint_positions, left_hand_task, fingertip_forces, stage, previous_policy_actions]}
  direction: {action_groups: [direction], observation_groups: [joint_positions, pelvis_velocity, chair_geometry, previous_walk_command, stage, previous_policy_actions]}
