#genesis config stand

# Environment settings
#-------------------------------------------
sim: genesis
robots: [g1_slider_simple]
fix_base_link: true
task: chairmansimple #chairmansimplegrpo # use chairmansimplegaussiangrpo for Gaussian-splat visual room
decimation: 5
num_envs: 100
headless: true
add_table: true
env_spacing: 4.0
train_or_eval: eval  #load_and_train #train_dagger #eval_video #eval_dagger_video #train_grpo #eval_grpo_video

# Train or Eval settings
#-------------------------------------------
force: false

#Eveluation settings
#------------------------------------------
#load_model_path:
eval_episodes: 100
eval_max_steps: 1000
eval_total_step_cap: 1000
eval_count_timeouts_as_failures: true

# Managed by run_chairman_training_pipeline.py
load_model_path: "./config_run/output/training_pipeline/run_2026-08-24_15-51-41/ppo"
