#genesis config stand

# Environment settings
#-------------------------------------------
sim: genesis
robots: [g1_slider_simple]
fix_base_link: true
task: chairmansimple #chairmansimplegrpo # use chairmansimplegaussiangrpo for Gaussian-splat visual room
decimation: 5
num_envs: 1
headless: false
add_table: true
env_spacing: 4.0
train_or_eval: eval_video  #load_and_train #train_dagger #eval_video #eval_dagger_video #train_grpo #eval_grpo_video

# Train or Eval settings
#-------------------------------------------
force: false

cameras:
   camera1:
     type: PinholeCameraCfg
     params:
       name: camera0
       pos: [-4.0, -4.0, 4.0]
       look_at: [0.0, 0.0, 0.0]
       width: 1024 #128
       height: 640 #128

#Eveluation settings
#------------------------------------------
#load_model_path:
eval_episodes: 100
eval_max_steps: 1000
eval_total_step_cap: 1000
eval_count_timeouts_as_failures: true

# Managed by run_chairman_training_pipeline.py
#load_model_path: ./config_run/output/ppo_model/run_2026-05-06_18_chairmansimple/model_560344000
load_model_path: "./config_run/output/ppo_models/run_2026-08-17_22_chairmansimple/model_500400000"
video_save_path: "./config_run/output/eval_videos/chair_man_ppo.mp4"
