#genesis config stand

# Environment settings
#-------------------------------------------
sim: genesis
robots: [g1_slider_simple]
fix_base_link: true
task: chairmansimple #chairmansimplegrpo # use chairmansimplegaussiangrpo for Gaussian-splat visual room
decimation: 5
num_envs: 9000
headless: true
add_table: true
env_spacing: 4.0
train_or_eval: train  #load_and_train #train_dagger #eval_video #eval_dagger_video #train_grpo #eval_grpo_video

force: false


# PPO training settings
#-------------------------------------------
total_timesteps: 1_000_000_000
model_save_path: ./config_run/output/ppo_models
model_save_freq: 10_000_000
tensorboard_log: ./config_run/output/ppo_models/tensorboard


# PPO parameters
#-------------------------------------------
net_arch_pivf: true
net_arch_pi: [128, 128, 128]
net_arch_vf: [128, 128, 128]

learning_rate: 0.0003
n_steps: 32
batch_size: 8192
n_epochs: 5
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.002
vf_coef: 1.0
max_grad_norm: 1.0
